### ISSUE TITLE
In Queue

### ISSUE THREAD

**Issue by Dispersia** [SightstoneOfficial/LegendaryClient#161]
In Queue now stays at the top even during champ select and while ingame and all the way through, needs removed on joining champ select and readded if terminated.

**Comment by ghost** [comment]
Also experiencing this issue.

**Comment by Zer0code** [comment]
I like it to be above content area as it now :) There is another bug that if you have a player queueing with you who has had luck to be marked for low priority queue (new dodge penalty since this patch) that you can not queue with LC with this player because the displayed window does not allow you to accept queue instead it is the window which is normally displayed if the client shiws you that you recently dodged and got a time penalty of X time [sounds complicated i know - just ask me in irc if i am online there]
