### ISSUE TITLE
How to build a release version?

### ISSUE THREAD

**Issue by atjeff** [SightstoneOfficial/LegendaryClient#223]
I'm having serious problems packaging as an exe. It seems like files are being pulled from your github account. Can you offer any insight ?

**Comment by eddy5641** [comment]
Try forking it than pulling from that

**Comment by Dispersia** [comment]
Closing as this doesn't really have to do with the project, but just C# in general.

 Anyway, to compile it, fork or clone this repo. Open the .sln file in visual studios and hit the build button at the top. If you want a release build instead of debug simply change the dropdown box from Debug -> Release, and that should be good. Once you hit the 'start' button, the exe will be created and dropped into LegendaryClient/LegendaryClient/Bin/Release, where you will find everything you need for the binary.
