### ISSUE TITLE
 If you made a commit yesterday-today

### ISSUE THREAD

**Issue by Dispersia** [SightstoneOfficial/LegendaryClient#274]
Move it back over. The packages thing killed the graph and made half of the repo unresponsive (and I'm surprised they didn't kill this repo until it was fixed). Only move the needed things over (again, please don't touch the packages, that's nugets job as everyone will have different package data).

 I created a branch backup, if you don't remember what was done, so don't worry your work wasn't lost.

**Comment by NitroXenon** [comment]
Everyone may have same version if you specific a version number in package.config

**Comment by Dispersia** [comment]
Each nuget package contains information on current OS, VS version and if you have team foundation installed, even the commit version, so you would be uploading the xml files every single time anyone wanted to commit, which would eventually cause conflict issues and a massive xml file (and if you saw the amount of lines, it was like over a million, it actually killed the graph on github).

**Comment by voshond** [comment]
yeah after the update everything was fucked on mine.

**Comment by NitroXenon** [comment]
oh sorry about that it's my bad. apologize to all devs

**Comment by NitroXenon** [comment]
@Dispersia Commit d3431d4 on branch Backup-Master-15/03/2015 broke the project because I forgot to decomment the package in .gitignore. Therefore the commit tracked all file in packages folder.

In my past few commit before d3431d4 I just add the DLLs requires by LC in packages. All I have done is just adding the DLLs manually in order to make Appveyor builds successfully. 

In conclusion, commits before d3431d4 work perfectly and Appveyor builds successfully.

**Comment by Dispersia** [comment]
Good good, and ya you don't have to apologize, I've done much worse on this repo, yours was like a 2 minute fix haha. Not a big deal
