### ISSUE TITLE
Going to make LC allows custom chat status

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#289]
Going to make LC allows editing raw chat status (you can customize your tier, game status etc.). I think its a interesting function.

Decide wheather make this for everyone or only devs.

Any opinion?

**Comment by secretdataz** [comment]
inb4 banhammer lol

**Comment by Phorofor** [comment]
That would be interesting to mess around with friends LOL. Maybe let anyone use it since it's actually not going to affect queues / gameplay and what not. Just maybe put a warning on it before allowing anyone use it.
.
I've seen someone use such status changers to place ASCII art on it before and make it seem like they were "stuck in Bronze" but they really weren't.

**Comment by nongnoobjung** [comment]
@secretdataz  คิดว่าไม่น่าโดนเพราะตอนนี้ยังไงก็สามารถconnectได้จาก พวกpidginอยู่แล้วด้วยGasToken

ถ้าเมื่อก่อน ใช้แค่uid loginไปลบ friend listใครก็ได้ที่เรามีuid เทพซ่ามาก

**Comment by eddy5641** [comment]
I think you can have it public because any xmpp chat app can do it

**Comment by NitroXenon** [comment]
yes, using pidgin to edit your status has a big problem : your status will be restored to default after you logged in using riot client. So I decided to integrate that function in LC.

**Comment by newchild** [comment]
The rank changer in devmode in fact allows this in a very limited way. But we agreed to make it dev only. The question is, should this be public?

**Comment by horato** [comment]
nope, you still need some knowledge to do it in xmpp. You don't need to stick it into user's face. Rito might mind.

**Comment by voshond** [comment]
seems to be dead.
