### ISSUE TITLE
Garena login sniff

### ISSUE THREAD

**Issue by nairaner** [SightstoneOfficial/LegendaryClient#366]
We should make separate background program to run with elavated priviliges, no point doing it for the whole client

**Comment by NitroXenon** [comment]
Okay I'll revert it first.

**Comment by NitroXenon** [comment]
Maybe make a starter for Garena users. That starter will only start LC with elavated priviliges that exit automatically.

**Comment by nairaner** [comment]
That would still make whole client run as admin and we dont need it

**Comment by NitroXenon** [comment]
Wat? The current garenaLogin method in login page also makes the whole client has elevated privileges...

**Comment by NitroXenon** [comment]
Okay we should better think of another method to do this...

**Comment by eddy5641** [comment]
Use the older complex method?
User launches LC and logs into garena
LC replaces lol.exe with a program that will launch (or you will be missing all the client stuff)
User goes onto garena client and signs in
Garena launches LC (Well a program that just launches lc because it may be in a different location)

This method is longer to implement but does not require any programs to be elevated

**Comment by secretdataz** [comment]
The old method casue issues when patching.

**Comment by Dispersia** [comment]
My question is just, why? If they have to give something admin, why does it matter if it's the whole application or not? Sure, we don't need it, but it's not like it hurts if we do

**Comment by secretdataz** [comment]
Agreed with @Dispersia. I don't even care.
