### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by Dispersia** [SightstoneOfficial/LegendaryClient#369]
Well first things first, glad to see this project getting worked on again. Kind of forgot about it but glad to see everyone is working on it again so good job everybody! With that said, wanted to know the direction you all wanted to go? Some things I thought of were like

-Change the name, it sounds OK but its like it was made in early 2000's, and its pretty pretentious lol.
-Ditching MahApps and writing our own frontend. MahApps is good and I love it but I don't feel its targeted towards something like a game client. Metro makes it look clean, but its also very plain, which is good for some things but again I don't think it fits the client the best.
-maybe organized rankings? Just a thought, but we don't really have a 'who's saying goes' system, I don't know how I feel about this one so input appreciated.

But again, good job everyone on working on this, I'm excited for the project again

**Comment by newchild** [comment]
Add ditching Jabber.net

**Comment by NitroXenon** [comment]
I think we need to make LC more customizable so that users can change background, sounds, color or ui of LC.

**Comment by Dispersia** [comment]
Wait nitro you've been here for a while lol, you can do all of that, or is that sarcasm and its going over my head

**Comment by eddy5641** [comment]
I am working on removing Jabber-net and replacing it with agsxmpp

**Comment by secretdataz** [comment]
Please do it on a separate branch for love of the god.

**Comment by secretdataz** [comment]
About the design. How about Google's material design?
Metro looks too flat imo.

**Comment by NitroXenon** [comment]
Material Design is awesome.

Well I'm going to implement these features :
1. Random skin in champion selection
2. Chat appear offline
3. Customizable client
4. more...

**Comment by Dispersia** [comment]
1. And 3. Are already done

**Comment by Dispersia** [comment]
2\* stupid phone

**Comment by secretdataz** [comment]
1. Can be done by adding a random skin button and select a skin randomly without telling the user.
2. and 3. are done.

**Comment by NitroXenon** [comment]
Adding a new item in SkinSelectListView is better imo.

**Comment by NitroXenon** [comment]
Sorry I just recognized that those 2 are already done. sorry...

**Comment by NitroXenon** [comment]
Just googled material design for .net, this library is available for wpf :
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit

**Comment by Dispersia** [comment]
You don't have to be sorry :P we are just saying don't waste your time haha. And ya, I think having a mystery skin in the list view would be good, like how LES does it.

**Comment by NitroXenon** [comment]
Also I think it is possible to implement skinny bot in LC becuz LES can do it... Just add a property called "lastSelectedSkinIndex" in BotParticipant and change the value :)

**Comment by voshond** [comment]
My thoughts about Design:

I've looked carefully at the Material design that Google is proving at the moment with this particular material Design. I somewhat disagree here. I approve that there lots of things we can improve! But here is what I think. There is not UI Framework that is gonna fix bad layouting and bad design language overall. The Client is a mixture of pragmatism and developers forging a somewhat working prototype so far, I used it to get to know some xaml and c# while others just have fun improving their c#, and there is nothing wrong with it.

I think the client doesn't really have to be blamed by mahapps or material design rather than the inconsistency of the design concept, if you can call randomly placed menus a concept at all. I won't question the logic, which is there, but to make the client feel "awesome" it's has to have a certain unity in spaces and menus, colours and text. Right now is just a building site which lots of different stuff. A user might go from homescreen to champselect and sees tremendous change in design language.

I have some time now and I'm currently drawing some UI concepts and making some research about good UI and thinking hard of what I can do better, yet I'm somewhat alone the UI guy it seems and I hope you guys will support me by making some changes happen that I'm alone might not be capable of at the moment due my lack of c# experience.

So before we jumpstart into ditching mahapps i would be more than happy to hear your thoughts on this one.

**Comment by Dispersia** [comment]
No I agree almost completely. We need to have a uniform design which usually ends up as either a specification or a single persons design that people learn off of. Either way, I understand ditching mahapps doesn't fix the issue, but its a start. A game client shouldn't be plain and flat, once its not boring, organize its looks, etc if you know what I mean

**Comment by voshond** [comment]
Well than I'm gonna need some help removing mahapps and implementing something new. Right now I didn't find much frameworks and I don't think I'm completely able to design all UI elements myself and building a framework myself. The layout is already in work as I'm sitting here with pen and paper.

**Comment by voshond** [comment]
@Dispersia quite nice you are back btw :b

**Comment by voshond** [comment]
I was thinking about other Names aswell sometimes. 
i came up with:
- Rift
- Riftclient
- BaronPit
- Sightstone

not sure but they are somewhat related to LoL, but whatever Names are always a huge debate

**Comment by nairaner** [comment]
Rift already is used by another game so we would be hard to find

**Comment by nairaner** [comment]
I like the Sightstone

**Comment by voshond** [comment]
its my fav too, i think it has a positive relation, everybody loves sightstone

**Comment by newchild** [comment]
+Sightstone

**Comment by voshond** [comment]
i think we are done about deciding and evolving.
