### ISSUE TITLE
Should we raise awareness with a post on reddit or whatever once we reach 4.0?

### ISSUE THREAD

**Issue by newchild** [SightstoneOfficial/LegendaryClient#398]
Ye or Naw?
I guess we would need to remove stuff like show enemy team in the "official" release then if we would raise awareness.
Also there would be the possibility of Riot rekking us.
Let's talk a little about this.

If we ever need it:
http://strawpoll.me/4891847

**Comment by secretdataz** [comment]
Ye, but we have to remove "hacky" functions or Rito will fuck us up.

**Comment by eddy5641** [comment]
I think that once all buggy stuff is gone and ddragon is gone that we can do it because its not like riot changes the calls everyday so even if riot shuts it down people can still use it. ddragon is very buggy and is usually a few hours behind patches. If it contains a new champ they have to wait for ddragon to be released

**Comment by voshond** [comment]
I think we could yes, but the App should be rock solid usable
